# Generated by Django 3.1.4 on 2025-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('rate', models.CharField(db_index=True, max_length=25, verbose_name='Оцека')),
                ('content', models.CharField(db_index=True, max_length=255, verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Оцека',
                'ordering': ['rate'],
            },
        ),
    ]
