# Generated by Django 3.1.4 on 2025-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_auto_20251104_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=100)),
                ('statistics', models.CharField(blank=True, max_length=25)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
