# Generated by Django 3.1.4 on 2025-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_auto_20251106_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
