# Generated by Django 3.1.4 on 2025-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_auto_20251106_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='rate',
        ),
        migrations.AddField(
            model_name='homework',
            name='athour',
            field=models.CharField(db_index=True, default=1, max_length=30, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='year',
            field=models.CharField(db_index=True, default=1, max_length=25, verbose_name='Год'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Текст'),
        ),
    ]
