# Generated by Django 3.1.4 on 2025-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_auto_20251108_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
    ]
