# Generated by Django 3.1.4 on 2025-11-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_auto_20251111_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerlogin',
            old_name='register',
            new_name='username',
        ),
    ]
