# Generated by Django 3.1.4 on 2025-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_auto_20251111_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='count',
            field=models.CharField(default=1, max_length=100, verbose_name='счетчик'),
            preserve_default=False,
        ),
    ]
