# Generated by Django 3.1.4 on 2025-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_women_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
