# Generated by Django 3.1.4 on 2025-11-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_auto_20251113_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
