# Generated by Django 3.1.4 on 2025-11-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_homework_newpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='video',
            field=models.FileField(default=1, upload_to='video/%Y/%m/%d/', verbose_name='видео'),
            preserve_default=False,
        ),
    ]
