# Generated by Django 3.1.4 on 2025-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0014_women_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d/', verbose_name='видео'),
        ),
    ]
