# Generated by Django 3.1.4 on 2025-11-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0015_auto_20251118_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
    ]
