# Generated by Django 3.1.4 on 2025-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0016_women_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='NewPage',
        ),
        migrations.DeleteModel(
            name='RegisterLogin',
        ),
        migrations.RemoveField(
            model_name='women',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
