# Generated by Django 3.1.4 on 2025-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0017_auto_20251220_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
    ]
