# Generated by Django 6.0 on 2026-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0021_saved_acc_alter_login_id_alter_tags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_acc',
            name='acuonts',
            field=models.JSONField(default=dict),
        ),
    ]
