# Generated by Django 5.2.7 on 2026-02-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0023_investedmoney_alter_login_id_alter_saved_acc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investedmoney',
            name='card_number',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
