# Generated by Django 5.2.7 on 2026-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0024_investedmoney_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='investedmoney',
            name='money_invested',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investedmoney',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
