# Generated by Django 5.2.7 on 2026-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0025_investedmoney_money_invested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_acc',
            name='acuonts',
        ),
        migrations.AddField(
            model_name='saved_acc',
            name='message',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_acc',
            name='messages',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_acc',
            name='user',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
