# Generated by Django 5.2.7 on 2026-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0026_remove_saved_acc_acuonts_saved_acc_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=10)),
                ('messages', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='saved_acc',
            name='message',
        ),
        migrations.RemoveField(
            model_name='saved_acc',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='saved_acc',
            name='user',
        ),
        migrations.AddField(
            model_name='saved_acc',
            name='acuonts',
            field=models.JSONField(default=dict),
        ),
    ]
