# Generated by Django 5.2.7 on 2026-03-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0027_chat_remove_saved_acc_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.JSONField(default=dict),
        ),
    ]
