# Generated by Django 5.2.7 on 2026-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0028_alter_chat_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveMesages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_freelancer', models.JSONField(default=list)),
                ('messages_client', models.JSONField(default=list)),
            ],
        ),
    ]
