# Generated by Django 5.2.7 on 2026-03-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0029_savemesages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
