# Generated by Django 5.2.7 on 2026-03-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0031_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='messages',
            field=models.CharField(max_length=100),
        ),
    ]
