# Generated by Django 5.2.7 on 2026-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0032_reviews_stars_alter_reviews_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='freelancer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
