# Generated by Django 5.2.7 on 2026-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0033_reviews_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_name', models.CharField(max_length=100)),
                ('clients', models.IntegerField()),
            ],
        ),
    ]
