# Generated by Django 5.2.7 on 2026-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0034_paymentsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_complain', models.CharField(max_length=250)),
                ('who_writing', models.CharField(max_length=50)),
                ('complain_about_who', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.CharField(max_length=100),
        ),
    ]
