# Generated by Django 5.2.7 on 2026-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0035_support_alter_reviews_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='accepted',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
