# Generated by Django 5.2.7 on 2026-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0037_moderatoraplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatoraplication',
            name='accepted_moder',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
