# Generated by Django 5.2.7 on 2026-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0038_moderatoraplication_accepted_moder'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
