# Generated by Django 5.2.7 on 2026-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0039_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='freelancers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
