# Generated by Django 5.2.7 on 2026-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0040_paymentsystem_freelancers'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='acceptde_role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
