# Generated by Django 5.2.7 on 2026-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0041_login_acceptde_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatoraplication',
            name='check_moderator',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
