# Generated by Django 5.2.7 on 2026-04-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0042_moderatoraplication_check_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='client_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
