# Generated by Django 5.2.7 on 2026-04-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0043_paymentsystem_client_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeratorAplication',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
