# Generated by Django 5.2.7 on 2026-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0044_delete_moderatoraplication_delete_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorAplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('accepted_moder', models.CharField(max_length=50)),
                ('check_moderator', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('violation', models.CharField(max_length=100)),
            ],
        ),
    ]
