# Generated by Django 5.2.7 on 2026-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=10)),
                ('messages', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='InvestedMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('money_invested', models.IntegerField()),
                ('card_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('acceptde_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorAplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('accepted_moder', models.CharField(max_length=50)),
                ('check_moderator', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('violation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('clients', models.IntegerField()),
                ('freelancers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=10)),
                ('messages', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saved_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuonts', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SaveMesages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_freelancer', models.JSONField(default=list)),
                ('messages_client', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_complain', models.CharField(max_length=250)),
                ('who_writing', models.CharField(max_length=50)),
                ('accepted', models.CharField(max_length=50)),
                ('complain_about_who', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
