from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', main, name='home'),
    path('login/', login, name='login'),
    path('redectar_freelancer/', redectar_freelancer, name='redectar_freelancer'),
    path('delete_msg_about_accepting_complain/', delete_msg_about_accepting_complain, name='delete_msg_about_accepting_complain'),
    path('checks_who_are_you/', checks_who_are_you, name='checks_who_are_you'),
    path('moving_you_to_window/', moving_you_to_window, name='moving_you_to_window'),
    path('remove_tag/', remove_tag, name='remove_tag'),
    path('add_tag/', add_tag, name='add_tag'),
    path('portfolio/', portfolio, name='portfolio'),
    path('add_page/', add_page, name='add_page'),
    path('project_1/', project_1, name='project_1'),
    path('project_2/', project_2, name='project_2'),
    path('acc_apply/', acc_apply, name='acc_apply'),
    path('invest_money/', invest_money, name='invest_money'),
    path('price_per_project/', price_per_project, name='price_per_project'),
    path('see_profile/', see_profile, name='see_profile'),
    path('hire_freelancer/', hire_freelancer, name='hire_freelancer'),
    path('chat_freelancer/', chat_freelancer, name='chat_freelancer'),
    path('save_messages/', save_messages, name='save_messages'),
    path('enter_chat/', enter_chat, name='enter_chat'),
    path('chat_customer/', chat_customer, name='chat_customer'),
    path('save_messages_2/', save_messages_2, name='save_messages_2'),
    path('enter_chat_2/', enter_chat_2, name='enter_chat_2'),
    path('check_tags/', check_tags, name='check_tags'),
    path('sort_by_tags/', sort_by_tags, name='sort_by_tags'),
    path('htmle/', htmle, name='htmle'),
    path('pythone/', pythone, name='pythone'),
    path('djangoe/', djangoe, name='djangoe'),
    path('csse/', csse, name='csse'),
    path('select_role/', select_role, name='select_role'),
    path('the_photo/', the_photo, name='the_photo'),
    path('upload_photo/', upload_photo, name='upload_photo'),
    path('reviews_from_customers/', reviews_from_customers, name='reviews_from_customers'),
    path('write_reviews/', write_reviews, name='write_reviews'),
    path('paying_system/', paying_system, name='paying_system'),
    path('searching_for_freelancers/', searching_for_freelancers, name='searching_for_freelancers'),

]
