# Generated by Django 5.2.7 on 2026-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestedMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('money_invested', models.IntegerField()),
                ('card_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saved_acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuonts', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_complain', models.CharField(max_length=250)),
                ('who_writing', models.CharField(max_length=50)),
                ('accepted', models.CharField(max_length=50)),
                ('complain_about_who', models.CharField(max_length=50)),
            ],
        ),
    ]
